name: My First Workflow
on:
  push:
    branches: 
    - main
  schedule:
    # Schedule triggers allow you to start a workflow at a scheduled time—they use the same syntax as cron jobs. The syntax consists of five fields that represent the minute (0–59), hour (0–23), day of month (1–31), month (1–12 or JAN–DEC) and day of week (0–6 or SUN–SAT). You can use the operators shown in
    # Runs at every 15th minute
    # - cron:  '*/15 * * * *'
    # Runs every hour from 9am to 5pm
    # - cron:  '0 9-17 * * *'
    # Runs every Friday at midnight
    # - cron:  '0 0 * * FRI'
    # Runs every quarter (00:00 on day 1 every 3rd month)
    - cron:  '0 0 1 */3 *'
  # manual triggers
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tag:
        description: 'Apply tag after successfull test run'
        required: true 
        type: boolean 
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  # this manual trigger is through API calls and be used to trigger multiple workflows with the same event
  # curl \ -X POST \ -H "Accept: application/vnd.github.v3+json" \ https://api.github.com/repos/{owner}/{repo}/dispatches \ -d '{"event_type":"event1"}'
  # Another example {"event_type":"event1","client_payload":{"passed":false,"message":"Error: timeout"}}
  repository_dispatch:
    types: [event1, event2]
  
# needs param will allow us to chain things together
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello world!"

    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: List files in a repository
      run: |
        echo "The repository ${{ github.repository }} contains the following ➥files:"
        tree
    - name: Manual trigger Workflow Inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "Homedrive: ${{ inputs.homedrive }}"
        echo "Log level: ${{ inputs.logLevel }}"
        echo "Tag Source: ${{ inputs.tags }}"
        echo "Environment: ${{ inputs.environment }}"
    - name: Manual trigger Repository Dispatch with additional payload namely client_payload in the object of event_type
      if: ${{ github.event_name == 'repository_dispatch' }}
      run: |
        echo "Payload: ${{ toJSON(github.event.client_payload) }}"
  
  MySecound_Parallel_Job:
    runs-on:  ubuntu-latest
    steps:
    - run: "echo Job: ${{ github.job }}"
    
  MyThird_Secound_parallel_sequence_Job:
    runs-on:  ubuntu-latest
    needs: [MySecound_Parallel_Job]
    steps:
    - run: "echo Job: ${{ github.job }}"

  MyForth_sequence_Job:
    runs-on: ubuntu-latest
    needs: [MySecound_Parallel_Job, MyThird_Secound_parallel_sequence_Job,MyFirstJob]
    steps:
      - run: "echo Job: ${{ github.job }}"
    
      
  
   
